codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 2%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default # update comment if already exists, otherwise post new
  require_changes: no
  require_base: no
  require_head: yes
