function(enable_coverage)
    if((CMAKE_CXX_COMPILER_ID STREQUAL "GNU") AND (CMAKE_C_COMPILER_ID STREQUAL "GNU"))
        set(CMAKE_BUILD_TYPE Debug)
        add_compile_options(--coverage)
        add_link_options(--coverage)
        link_libraries(gcov)
        message(WARNING "Enabling coverage with debug")
    else()
        message(WARNING "A coverage build was specified, but the CMAKE compiler is not GCC")
    endif()
endfunction()