#
# BSD 2-Clause License
#
# Copyright (c) 2021-2023, Hewlett Packard Enterprise
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

name: run_tests

# This file is for tests that are to be run frequently, with each push to a PR.

on:
  push:
    branches:
      - master
      - develop
      - codecov_clustered
  pull_request:
    branches:
      - master
      - develop

env:
  HOMEBREW_NO_ANALYTICS: "ON" # Make Homebrew installation a little quicker
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"
  DEBIAN_FRONTEND: "noninteractive" # disable interactive apt installs
  SSDB_SINGLE: "127.0.0.1:6380"
  SSDB_CLUSTERED: "127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002"
  SSDB_UDS: "unix:///tmp/redis.sock"
  SMARTREDIS_TEST_CLUSTER: False
  SR_LOG_FILE: "smartredis_cicd_tests_log.txt"
  SR_LOG_LEVEL: "INFO"

jobs:

  run_tests:
    name: Run smartredis tests using ${{ matrix.os }}, Python ${{ matrix.py_v }}, RedisAI ${{ matrix.rai_v }}, and compiler ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04] # cannot test on macOS as docker isn't supported on Mac
        rai_v: [1.2.5] # versions of RedisAI
        py_v: ['3.7.x', '3.8.x', '3.9.x'] # versions of Python
        compiler: [intel, 8, 9, 10, 11] # intel compiler, and versions of GNU compiler
    env:
      FC: gfortran-${{ matrix.compiler }}
      GCC_V: ${{ matrix.compiler }} # used when the compiler is gcc/gfortran

    # # Service containers to run with `container-job`
    # services:
    #   # Label used to access the service container
    #   redis:
    #     # Docker Hub image
    #     image: redislabs/redisai:${{ matrix.rai_v }}-cpu-bionic

    #     # Set health checks to wait until redis has started
    #     options: >-
    #       --health-cmd "redis-cli ping"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       # map port 6379 on service container to the host
    #       - 6379:6379

    steps:
      # download a copy of SmartRedis before running CI tests
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py_v }}

      # Install compilers
      - name: Install GCC
        if: "!contains( matrix.compiler, 'intel' )" # if using GNU compiler
        run: |
          sudo apt-get -y update &&
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test &&
          sudo apt-get -y update &&
          sudo apt-get -y install -y gcc-${GCC_V} gfortran-${GCC_V} g++-${GCC_V} &&
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
          --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
          --slave /usr/bin/g++ g++ /usr/bin/g++-${GCC_V} \
          --slave /usr/bin/gcov gcov /usr/bin/gcov-${GCC_V} &&
          echo "CC=gcc" >> $GITHUB_ENV &&
          echo "CXX=g++" >> $GITHUB_ENV &&
          echo "FC=gfortran" >> $GITHUB_ENV

      - name: Install Intel compiler
        if: "contains( matrix.compiler, 'intel' )" # if using intel compiler
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB &&
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB &&
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB &&
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list &&
          sudo apt-get update -y &&
          sudo apt-get install -y intel-oneapi-compiler-fortran intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
          source /opt/intel/oneapi/setvars.sh &&
          printenv >> $GITHUB_ENV &&
          echo "CC=icc" >> $GITHUB_ENV &&
          echo "CXX=icpc" >> $GITHUB_ENV &&
          echo "FC=ifort" >> $GITHUB_ENV

      # Set up standalone Redis environment
      - name: Install Cmake Linux
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get -y install cmake

      - name: Build SmartRedis python and install
        run: python -m pip install -e .[dev,xarray]

      - name: Build and install dependencies
        run: |
            mkdir -p ./third-party &&
            cd ./third-party &&
            bash ../build-scripts/build-lcov.sh &&
            bash ../build-scripts/build-catch.sh

      - name: Install docker and redis-server
        run: |
          sudo apt-get -y update && sudo apt-get -y install curl gnupg lsb-release software-properties-common ca-certificates && \
          # Add latest redis to apt sources
          echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list && \
          curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg && \
          # Add latest docker to apt sources
          echo  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && \
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
          sudo apt-get -y update && \
          sudo apt-get -y install iputils-ping docker-ce docker-ce-cli containerd.io redis-tools=6:6.2.5-1rl1~focal1 redis-server=6:6.2.5-1rl1~focal1 &&
          docker create --name redisai --rm redislabs/redisai:${{ matrix.rai_v }}-cpu-bionic && \
          sudo mkdir -p /usr/lib/redis/modules/ &&
          sudo docker cp redisai:/usr/lib/redis/modules/redisai.so /usr/lib/redis/modules &&
          sudo docker cp redisai:/usr/lib/redis/modules/backends/ /usr/lib/redis/modules/ &&
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/install/lib" >> $GITHUB_ENV &&
          echo "REDISAI_MODULES=/usr/lib/redis/modules/redisai.so \
                TF /usr/lib/redis/modules/backends/redisai_tensorflow/redisai_tensorflow.so \
                TORCH /usr/lib/redis/modules/backends/redisai_torch/redisai_torch.so" >> $GITHUB_ENV

      - name: Single-shard DB tests
        run: |
          SCRATCH_DIR="single_scratch"
          rm -rf $SCRATCH_DIR; mkdir $SCRATCH_DIR; pushd $SCRATCH_DIR &&
          redis-server --port 6380 --daemonize yes \
                       --logfile "single.log" \
                       --loadmodule $REDISAI_MODULES &&
          sleep 5; cat single.log &&
          popd &&
          export SSDB=$SSDB_SINGLE SMARTREDIS_TEST_CLUSTER=False &&
          make test-verbose COV_FLAGS="--cov=./src/python/module/smartredis/ --cov-report=xml --cov-append"

      - name: Clustered DB tests
        run: |
          SCRATCH_DIR="cluster_scratch"
          rm -rf $SCRATCH_DIR; mkdir $SCRATCH_DIR; pushd $SCRATCH_DIR &&
          for port in {7000..7002}; do
            redis-server --port $port --cluster-enabled yes --daemonize yes \
                         --cluster-config-file "$port.conf" --protected-mode no --save "" \
                         --logfile "$port.log" \
                         --loadmodule $REDISAI_MODULES
          done &&
          sleep 2 &&
          redis-cli --cluster create $(echo $SSDB_CLUSTERED | tr "," " ") --cluster-yes &&
          export SSDB=$SSDB_CLUSTERED SMARTREDIS_TEST_CLUSTER=True &&
          popd &&
          python -m pytest --cov=./src/python/module/smartredis/ --cov-report=xml --cov-append \
                 --ignore ./tests/docker -vv -s ./tests

      - name: UDS DB tests
        run: |
          mkdir -p /tmp && ## Create socketfile for UDS testing
          touch /tmp/redis.sock &&
          chmod 777 /tmp/redis.sock &&
          SCRATCH_DIR="uds_scratch" &&
          rm -rf $SCRATCH_DIR; mkdir $SCRATCH_DIR; pushd $SCRATCH_DIR &&
          redis-server --unixsocket /tmp/redis.sock --unixsocketperm 777 --port 0 --bind 127.0.0.1 \
                       --daemonize yes --protected-mode no --logfile "uds.log" \
                       --loadmodule $REDISAI_MODULES &&
          popd &&
          export SSDB=$SSDB_UDS SMARTREDIS_TEST_CLUSTER=False &&
          python -m pytest --cov=./src/python/module/smartredis/ --cov-report=xml --cov-append \
                 --ignore ./tests/docker -vv -s ./tests

      - name: Collect C++ coverage
        run: third-party/lcov/install/usr/local/bin/lcov -c -d build/CMakeFiles -d tests -o coverage.info

      # Upload final coverage reports
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml, ./coverage.info